### ISSUE TITLE
pop a check into Shortcodes.php 

### ISSUE THREAD

**Issue by ChippyWhips** [wp-kit/theme#3]
Line 101. Do the magic.

![screen shot 2017-08-15 at 16 53 16](https://user-images.githubusercontent.com/10211530/29323998-9f24f696-81da-11e7-9926-f9d7778e3747.png)

**Comment by terence1990** [comment]
@CreativeLittleChris please paste in code and do not send screenshots, really not helpful

**Comment by terence1990** [comment]
@CreativeLittleChris also these should be posted on https://github.com/wp-kit/core

**Comment by terence1990** [comment]
is done please user version ```1.5.6``` 

https://github.com/wp-kit/core/releases
