### ISSUE TITLE
Make THEME_URI available in twig files

### ISSUE THREAD

**Issue by ChippyWhips** [wp-kit/theme#4]
Hello, 

I'm sure you will tell me there is already a wonderful way to do this that I don't know about, but I had to add this in so that I could access THEME_URI in my .twig files. If this is no good then don't add it obviously, but if there is no way to do this currently then it would be good to have something like this added in. 

File changed: `app/Services/Shortcode.php`
Line added: `87`

![screen shot 2017-08-16 at 09 49 28](https://user-images.githubusercontent.com/10211530/29355345-9a8eb2fa-8268-11e7-9244-0a3929aff93e.png)

**Comment by terence1990** [comment]
Hey Chris,

You can use ```context``` argument

```
// initialise WPKit to invoke classes etc. - turn off autoTimber
wpkit()->autoTimber = false;
wpkit()->boot();
	
// define some integrations, both WPKit Core & WPKit
wpkit()->addIntegrations(array(
   'timber-library' => array(
     'file' => 'timber-library/timber.php',
      'context' => array(
          'path' => THEME_URI
      )
   )
));
```

Make sure you use version ```1.5.6```

https://github.com/wp-kit/core/releases/tag/1.5.6
