### ISSUE TITLE
Error thrown on clean install

### ISSUE THREAD

**Issue by mattpilott** [wp-kit/theme#8]
Okay, so i downloaded the latest version from github and ran the command suggested in the readme.md which all worked well. However when I checked it in the browser I was presented with an error coming from the test widget. I realise this is a dummy thing but thought it probably shouldn't throw an error

<img width="1680" alt="screen shot 2018-06-14 at 20 27 47" src="https://user-images.githubusercontent.com/2401925/41433954-32aad95a-7012-11e8-9073-34fefa9a3d1f.png">

**Comment by terence1990** [comment]
@matt3224 this was a bug in 2.0.0 which has been fixed since and the version is current 2.0.3, so you can run:

`composer create-project wp-kit/theme=2.* theme --prefer-dist`

I have updated the read me
